name: My CI_CD workflow

# my trigger
on:
- push

jobs:
  # name of may job
  SA58 Team7 DAI GAOLUO CI_CD:
    #runner
    runs-on: ubuntu-latest
    #steps in this job
    steps:
      - name: Scan the code base for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'