name: My CI_CD workflow

# my trigger
on:
  push:
    branches:
    - master
    tags:
    - 'release/v[0-9]+.[0-9]+'

jobs:
  # add comments to verify the commit check funciton
  CI_CD_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
 
      - name: Get Latest Commit Message
        id: commit_message
        run: echo "::set-output name=message::$(git log -1 --pretty=format:'%s')"
 
      - name: Stop Workflow # if Commit Message Starts with 'NORUN'
        if: startsWith(steps.commit_message.outputs.message, '#NORUN')
        run: |
          echo "Commit message starts with #NORUN, stopping workflow."
          exit 0
          
      - name: Checkout code
        uses: actions/checkout@v3
      
      # - name: Run Trivy vulnerability scanner in fs mode
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     scan-type: 'fs'
      #     scan-ref: '.'
      #     trivy-config: trivy.yaml
      #     severity: 'CRITICAL'
      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          hide-progress: true
          output: trivy.txt

      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy.txt ]]; then
            {
              echo "### Security Output"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```terraform'
              cat trivy.txt
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi
     
      # notification to slack
      - name: Slack Notification When trivy failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: 'Scan failed - DAI GAOLUO'
          SLACK_MESSAGE: 'failed trivy scan, see uploaded report'
          SLACK_COLOR: 'failure'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEST_URL }}  

      - name: Slack Upload Trivy
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'trivy.txt'
          initial_comment: 'post by slack-upload-file'
      
      - name: Slack Notification When trivy success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: 'Image build and signed'
          SLACKIFY_MARKDOWN: 'true'
          SLACK_MESSAGE: 
            '**Name**: DAI GAOLUO \n
            **Metriculation**: A0292132M \n
            **Email**: [e1338594@u.nus.edu](e1338594@u.nus.edu) \n
            **Git**: ${{ github.server_url }}/${{ github.repository }} \n
            **Image**: [not yet]()'
          SLACK_COLOR: 'success'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEST_URL }}  