name: My CI_CD workflow

# my trigger
on:
  push:
    branches:
    - master
    tags:
    - 'release/v[0-9]+.[0-9]+'

jobs:
  # add comments to verify the commit check funciton
  Check_commit_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
 
      - name: Get Latest Commit Message
        id: commit_message
        run: echo "::set-output name=message::$(git log -1 --pretty=format:'%s')"
 
      - name: Stop Workflow # if Commit Message Starts with 'NORUN'
        if: startsWith(steps.commit_message.outputs.message, '#NORUN')
        run: |
          echo "Commit message starts with #NORUN, stopping workflow."
          exit 0
  
  # name of may job
  Scan_the_code_base_for_vulnerabilities:
    #runner
    runs-on: ubuntu-latest
    #steps in this job
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: trivy.yaml
  
  # notification to slack
  Send_GitHub_Action_trigger_data_to_Slack_workflow:
  id: slack
  uses: slackapi/slack-github-action@v1.26.0
  env:
    SLACK_WEBHOOK_TEST_URL: ${{ secrets.SLACK_WEBHOOK_TEST_URL }}