name: My CI_CD workflow

# my trigger
on:
- push

jobs:
  # name of may job
  SA58_Team7_DAI_GAOLUO_CI_CD:
    #runner
    runs-on: ubuntu-latest
    #steps in this job
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: trivy.yaml